<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{{ asset('assets/frontend/assets/vendors/bootstrap/js/bootstrap.bundle.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/clipboard/clipboard.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/vanilla-lazyload/lazyload.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/waypoints/jquery.waypoints.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/lightgallery/lightgallery.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/lightgallery/plugins/zoom/lg-zoom.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/lightgallery/plugins/thumbnail/lg-thumbnail.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/lightgallery/plugins/video/lg-video.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/lightgallery/plugins/vimeoThumbnail/lg-vimeo-thumbnail.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/isotope/isotope.pkgd.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/slick/slick.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/gsap/gsap.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/gsap/ScrollToPlugin.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/gsap/ScrollTrigger.min.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/vendors/mapbox-gl/mapbox-gl.js')}}"></script>
<script src="{{ asset('assets/frontend/assets/js/theme.min.js')}}"></script>
